### ISSUE TITLE
Importing kuvio blows up Astro (astro dev)

### ISSUE THREAD

**Issue by dearlordylord** [skeate/kuvio#13]
- setup Astro with all defaults https://docs.astro.build/en/install-and-setup/
- add ```import * as k from 'kuvio';
k.exactString('test');``` to Index.astro
- run `npx astro dev`
- index page hangs and never loads

I found this issue through using a react component with schemata-ts imported. Although the example is not a real use case, it shows that kuvio can hang Astro setups through being imported as a dependency of another library.

Reproduction: https://github.com/dearlordylord/kuvio-astro-hang

**Comment by skeate** [comment]
Thanks for the reproduction!

It looks like this is because kuvio exports a function called `then`, and I'm guessing something in the build pipeline expects `then` to mean it's a `Promise`. I'm not 100% clear but it looks like it's something in the Node built-ins that's doing this?

It feels pretty ridiculous that this is a problem. Thanks, designers of Promises!

I can rename the function, though `then` is used all over the place so it's going to be a breaking change. I'll also send a patch to schemata-ts

**Comment by dearlordylord** [comment]
@skeate thanks for checking this! .then issue is funny indeed, I wonder if it's Astro bug actually

I re-checked Schemata itself (without explicit kuvio import) just to be sure: it seems it *doesn't* hang the page. Schemata uses kuvio in definitions though so explicit import `kuvio` is unavoidable sometimes

**Comment by skeate** [comment]
You should be able to upgrade schemata-ts to `2.2.5` now to fix this

https://github.com/jacob-alford/schemata-ts/releases/tag/2.2.5
